name: comment

on:
  issue_comment:
    types: [created]

jobs:
  comment:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/execute')
    steps:
      - run: |
          echo "hello"
