on:
  pull_request:
    types: opened

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "test: ${{ true && false && github.ref }}"
  reuse:
    uses: ./.github/workflows/zizmor-issue-646.yml
