on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${stuff}"
        env:
          stuff: ${{ format('{0}', tojson(SECRETS)) }}
      - uses: actions/checkout
      - uses: ./.github/actions/test
